name: pacstrap
description: 036pacstrap
version: 1.0.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  console: ^4.1.0
  fpdart: ^1.1.0
  internet_connection_checker: ^1.0.0+1
  system_info2: ^4.0.0
  zerothreesix_dart: ^0.1.2

dev_dependencies:
  lints: ^3.0.0