name: pacstrap
description: 036pacstrap
version: 1.0.0

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  console: ^4.1.0
  dcli: ^2.0.1
  fpdart: ^0.5.0
  get_it: ^7.2.0
  internet_connection_checker: ^1.0.0+1
  system_info2: ^3.0.1

dev_dependencies:
  lints: ^2.0.1